function kom1(){
    document.getElementById("kom1").style.display = "none"
    document.getElementById("odp1").style.display = "none"
     document.getElementById("kom2").style.display = "none"
    document.getElementById("odp2").style.display = "none"
     document.getElementById("kom3").style.display = "none"
    document.getElementById("odp3").style.display = "none"
     document.getElementById("kom4").style.display = "none"
    document.getElementById("odp4").style.display = "none"
     document.getElementById("kom5").style.display = "none"
    document.getElementById("odp5").style.display = "none"
     document.getElementById("kom6").style.display = "none"
    document.getElementById("odp6").style.display = "none"
    document.getElementById("kom2").style.display = "flex"
    document.getElementById("odp2").style.display = "flex"
}

function kom2(){
    document.getElementById("kom1").style.display = "none"
    document.getElementById("odp1").style.display = "none"
    document.getElementById("kom2").style.display = "none"
    document.getElementById("odp2").style.display = "none"
    document.getElementById("kom3").style.display = "flex"
    document.getElementById("odp3").style.display = "flex"
    document.getElementById("kom4").style.display = "none"
    document.getElementById("odp4").style.display = "none"
     document.getElementById("kom5").style.display = "none"
    document.getElementById("odp5").style.display = "none"
     document.getElementById("kom6").style.display = "none"
    document.getElementById("odp6").style.display = "none"
}

function kom3(){
    document.getElementById("kom1").style.display = "none"
    document.getElementById("odp1").style.display = "none"
    document.getElementById("kom2").style.display = "none"
    document.getElementById("odp2").style.display = "none"
    document.getElementById("kom3").style.display = "none"
    document.getElementById("odp3").style.display = "none"
    document.getElementById("kom4").style.display = "flex"
    document.getElementById("odp4").style.display = "flex"
    document.getElementById("kom5").style.display = "none"
    document.getElementById("odp5").style.display = "none"
     document.getElementById("kom6").style.display = "none"
    document.getElementById("odp6").style.display = "none"
}

function kom4(){
    document.getElementById("kom1").style.display = "none"
    document.getElementById("odp1").style.display = "none"
    document.getElementById("kom2").style.display = "none"
    document.getElementById("odp2").style.display = "none"
    document.getElementById("kom3").style.display = "none"
    document.getElementById("odp3").style.display = "none"
    document.getElementById("kom4").style.display = "none"
    document.getElementById("odp4").style.display = "none"
    document.getElementById("kom5").style.display = "flex"
    document.getElementById("odp5").style.display = "flex"
     document.getElementById("kom6").style.display = "none"
    document.getElementById("odp6").style.display = "none"
}

function kom5(){
    document.getElementById("kom1").style.display = "none"
    document.getElementById("odp1").style.display = "none"
    document.getElementById("kom2").style.display = "none"
    document.getElementById("odp2").style.display = "none"
    document.getElementById("kom3").style.display = "none"
    document.getElementById("odp3").style.display = "none"
    document.getElementById("kom4").style.display = "none"
    document.getElementById("odp4").style.display = "none"
    document.getElementById("kom5").style.display = "none"
    document.getElementById("odp5").style.display = "none"
    document.getElementById("kom6").style.display = "flex"
    document.getElementById("odp6").style.display = "flex"
}

function kom6(){
    document.getElementById("kom2").style.display = "none"
    document.getElementById("odp2").style.display = "none"
    document.getElementById("kom3").style.display = "none"
    document.getElementById("odp3").style.display = "none"
    document.getElementById("kom4").style.display = "none"
    document.getElementById("odp4").style.display = "none"
    document.getElementById("kom5").style.display = "none"
    document.getElementById("odp5").style.display = "none"
    document.getElementById("kom6").style.display = "none"
    document.getElementById("odp6").style.display = "none"
    document.getElementById("kom1").style.display = "flex"
    document.getElementById("odp1").style.display = "flex"
}